### ISSUE TITLE
Documentation for multi-repo deployments

### ISSUE THREAD

**Issue by sc250024** [justinbarrick/flux-operator#32]
Filing this under "Issues", though I'm mostly wondering if this use case is possible. I've been experimenting with this Flux operator, and would be happy to create the PR myself to document this kind of use case. 

Basically, I'm trying to create a CLI tool for our developers by which they can spin up temporary test environments. The idea would be that they would work on some feature branch `feature/some-new-thing`, and that the CLI tool would be a wrapper for this Flux operator. I know `skaffold` already exists for this case, but we're not using a monorepo, and I like the idea of using Flux a lot more.

Let's say we have three repos that make up our standard stack:

- company/repo1
- company/repo2
- company/repo3

The CLI tool, upon creation (`mytool create tempenv feature/some-new-thing`) would check each of the defined repositories above, looking for the branch `feature/some-new-thing` in each of those repositories. If it finds the branch exists, it would then create a `Flux` resource with `gitBranch: feature/some-new-thing`; if it doesn't find it, it would fall back to `master` as a default. The tool would also create a custom namespace for `some-new-thing`. 

For all of the repos, we're also using Helm charts, which each repository has in the directory `charts/repoX`. My questions are:

- Since I have three Helm-based repositories, does that mean I also need three separate tillers? When creating the resource `kind: Flux`, I noticed the following line: "If Tiller does not already exist in the namespace, also set `tiller.enabled: true`".
- I didn't notice in the documentation any support for a centralized Tiller. If I already have Tiller running in `kube-system`, do I still need to create a Tiller instance just for this namespace?
- In general, is this type of workflow suitable for this `flux-operator` project? I tried creating a sample case based on the flow I described above, and after creating the corresponding `FluxHelmRelease`s, I noticed that things didn't work as expected.

Some guidance on this would be appreciated. As mentioned before, would be happy to update documentation :)

**Comment by justinbarrick** [comment]
> the CLI tool would be a wrapper for this Flux operator. 

We currently have [fluxopctl](https://github.com/justinbarrick/flux-operator#using-fluxopctl) for installing the operator itself - I also wanted to expand it to have a subcommand to help make flux instances. I'm not sure if it makes sense for you to contribute your tool upstream here (for example, if you're checking branches that's gonna be specific to your git server and it might be a pain to implement it for all of the major ones), but I'm definitely open to ideas!

> Since I have three Helm-based repositories, does that mean I also need three separate tillers? When creating the resource kind: Flux, I noticed the following line: "If Tiller does not already exist in the namespace, also set tiller.enabled: true".

Yeah, you'd use three different tillers there. And actually, that doc actually seems to be wrong - it's currently *only* possible to use a Tiller deployed by flux-operator since we hardcode the hostname: https://github.com/justinbarrick/flux-operator/blob/master/pkg/helm-operator/helm_operator.go#L58-L60

> I didn't notice in the documentation any support for a centralized Tiller. If I already have Tiller running in kube-system, do I still need to create a Tiller instance just for this namespace?

Also not possible yet, but there's no reason we can't make the tiller settings here more flexible - I think we can use this issue as the feature request for that.

> In general, is this type of workflow suitable for this flux-operator project? I tried creating a sample case based on the flow I described above, and after creating the corresponding FluxHelmReleases, I noticed that things didn't work as expected.

Definitely the type of workflow we want to support - it seems like the main issue would be the number of tillers, but I expect you'd be able to PoC as-is. What problems did you run into?

**Comment by sc250024** [comment]
@justinbarrick, thanks for the quick reply.

To go into a bit more detail, I'll show you what steps I did. All the relevant files are in this gist: https://gist.github.com/sc250024/b9ac6c57cfc584ac3ef4571e300a77c4

1. First create a test namespace `kubectl create ns fluxops-test`.

2. Deploy the YAML generated from `fluxopctl -cluster -tiller-version=v2.10.0 -flux-version="1.6.0" -git-secret="my-git-ssh-key"`. It's basically the same, except that I change the `namespace: default` to `namespace: fluxops-test`.

3. Deploy a `Flux` resource using the `concept` branch of `myapp` using the YAML in the gist. This branch also has an equivalent Docker image, also with the tag `concept`. 

4. Deploy a `FluxHelmRelease` of `myapp` with Helm chart values specified in the YAML manifest. Up until this point, everything works as expected.

Beyond here I'm not sure if the steps are correct:

5. Deploy a `Flux` resource using the `master` branch of `myotherapp`. Just like `myapp`, this also has a Docker tag `master` matching the branch name.	 This repo is also using a Helm chart.

6. Deploy a `FluxHelmRelease` of `myotherapp` with Helm chart values specified in the YAML manifest.

Step 6 is where things get weird. The Helm operator for `myotherapp` successfully creates a new pod like `fluxops-test-myotherapp-594f464f8-jcwf8`, but then it also tries to create `fluxops-test-myotherapp-myapprepo-5dccd5d668-f7pc7`. In short, what I'm trying to do is this:

- 1 container of `myapp:concept`
- 1 container of `myotherapp:master`

After step 6, it creates:

- 1 container of `myapp:concept`
- 1 container of `myotherapp:master`
- 1 container of `myapp:master`

In my case, `myapp` doesn't yet have a `master` tag in Docker, so understandably, that container fails with `ErrImagePull`.

**Comment by justinbarrick** [comment]
It looks like both of your Fluxes are in the same namespace and both can see the FluxHelmRelease you created. I think both of your helm-operators are using the FluxHelmRelease. Have you tried running them in separate namespaces?

**Comment by sc250024** [comment]
Yes, they are running the same namespace. My idea was that someone would create a temporary environment for that feature branch, and all related items would be inside one namespace. After testing is completed, we would just throw away the namespace for an easy cleanup.

You're saying if I have 5 microservices in my stack, I would have to create 5 separate namespaces for one test environment?

**Comment by justinbarrick** [comment]
No, I’m saying you should only have one helm-operator watching any given namespace. You can deploy as many services as you want with the helm-operator, but if you have two of them watching the same namespace, they will both try to deploy any FluxHelmReleases.

From your example before, it looks like you are trying to deploy both branches to the same namespace instead of having a namespace per branch.

**Comment by sc250024** [comment]
I see what you're saying regarding the multiple Helm operators. I agree that's what's happening: the Helm operator is picking up the other `FluxHelmRelease`, and trying to deploy a pod based on that. I _am_ trying to deploy all the services into one namespace, and based on what you said, then I only need one Helm operator in that namespace.

To make sure I understand the basics, correct me if I'm wrong on any of the following:
- For every microservice (and thus, Git repository since mine are separate) you want to deploy in one namespace, you need a `Flux` resource for that repository.
- If you want that microservice to be deployed using Helm, you also need a corresponding `FluxHelmRelease` resource for that repository to pass in values into the Helm chart.

What's now confusing me is this part:

```yaml
  helmOperator:
    chartPath: chart/myotherapp/
    enabled: true
    gitPollInterval: "0m30s"
```

Before I am saying `enabled: true` for all of the `Flux` resources I create. Does that mean, for a namespace where I deploy multiple microservices, that I only need to set `    enabled: true` for the first `Flux` instance, and then `enabled: false` for the remaining ones? Or how else would I deploy only one Helm Operator that knows about the multiple services I am deploying to the namespace, each with their own path to the Helm charts?

Sorry for the verbosity, I'm just trying to understand the relationship between how multiple repositories map to the creation of `Flux` resources. The flow is a bit confusing, which is why I'm trying to really understand it so I can write documentation for it.

**Comment by sc250024** [comment]
To explain a bit further, I took another look at the [weaveworks/flux-helm-test](https://github.com/weaveworks/flux-helm) repo. Specifically, this path with the multiple charts: https://github.com/weaveworks/flux-helm-test/tree/master/charts

My layout isn't like theirs; my charts all live within their respective repositories, like so...

```shell
$ tree -L 2
.
├── microservice-repo1
│   ├── Dockerfile
│   ├── Makefile
│   ├── helm/
│   ├── docker-compose.yaml
│   └── src/
├── microservice-repo2
│   ├── Dockerfile
│   ├── Makefile
│   ├── helm/
│   ├── docker-compose.yaml
│   └── src/
├── microservice-repo3
│   ├── Dockerfile
│   ├── Makefile
│   ├── helm/
│   ├── docker-compose.yaml
│   └── src/
├── microservice-repo4
│   ├── Dockerfile
│   ├── Makefile
│   ├── helm/
│   ├── docker-compose.yaml
│   └── src/
└── microservice-repo5
    ├── Dockerfile
    ├── Makefile
    ├── helm/
    ├── docker-compose.yaml
    └── src/
```

Does this imply I can't use Flux since my Helm charts are not neatly packaged into one repository?

**Comment by justinbarrick** [comment]
The typical pattern that people use with helm-operator is to put all of their charts into the same repository and then they use flux to automate the image tag updates on code updates - basically, you separate config and code.

You *can* store each chart in a different repository, but helm-operator doesn't support watching multiple repositories.

For that, you can use the flux-operator to help you manage all of the helm-operators that you need to watch each of those repositories. Unfortunately, there's not currently a clean way to have many helm-operators watch the same namespace - and, honestly, you probably don't want to do that, because that is a lot of helm-operators, fluxes, and tillers.

> For every microservice (and thus, Git repository since mine are separate) you want to deploy in one namespace, you need a Flux resource for that repository.

For every git repository that you want to watch, you need a Flux instance. These don't necessarily map to microservices (or even namespaces, if your flux has access to the full cluster).

> If you want that microservice to be deployed using Helm, you also need a corresponding FluxHelmRelease resource for that repository to pass in values into the Helm chart.

Yes.

> Or how else would I deploy only one Helm Operator that knows about the multiple services I am deploying to the namespace, each with their own path to the Helm charts?

You can deploy only a single helm-operator if all of the charts are in the same repository.

> Sorry for the verbosity, I'm just trying to understand the relationship between how multiple repositories map to the creation of Flux resources. 

They aren't related. One Flux equals one repository. If two Fluxes attempt to manage the same resources they will clash. The helm-operator is a bit more finky and you can only do one repository per namespace because of that.

**Comment by justinbarrick** [comment]
Have you tried out argo-cd? It might work better for your use-case: https://github.com/argoproj/ARGO-cd
